credentials:
  usernames:
    ahmet:
      email: ahmet@sirket.com
      name: Ahmet YÄ±lmaz
      password: "$2b$12$8P0SgI2SzroiMSmN59ufv.qmmj0n0m8Nkhf9eC78Do6bfJhEVTeku" 
    mehmet:
      email: mehmet@sirket.com
      name: Mehmet Demir
      password: "$2b$12$xJc9KcHBLEKwtgrGY1FYzetESp9VqUneBVCObAzO4mTWjuzAnlf76"

cookie:
  expiry_days: 1
  key: "random_signature_key_cok_gizli"
  name: "inhouse_login_cookie"